//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosGIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPorUsuario
    {
        public long idRolesPorUsuario { get; set; }
        public Nullable<long> idUsuario { get; set; }
        public Nullable<long> idRol { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
