//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosGIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RolesPorUsuario = new HashSet<RolesPorUsuario>();
        }
    
        public long idRol { get; set; }
        public string codigoRol { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<RolesPorUsuario> RolesPorUsuario { get; set; }
    }
}
