//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosGIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.RolesPorUsuario = new HashSet<RolesPorUsuario>();
        }
    
        public long idUsuario { get; set; }
        public string codigoUsuario { get; set; }
        public byte[] clave { get; set; }
        public string primernombre { get; set; }
        public string segundonombre { get; set; }
        public string primerapellido { get; set; }
        public string segundoapellido { get; set; }
        public string nombrecompleto { get; set; }
        public string correo { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaingreso { get; set; }
        public System.DateTime ultimoingreso { get; set; }
    
        public virtual ICollection<RolesPorUsuario> RolesPorUsuario { get; set; }
    }
}
